### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mateuszbialowas** [fnando/breadcrumbs#13]
## Description

I can't add breadcrumb related on params.  
<img width="1110" alt="CleanShot 2023-06-18 at 21 51 55@2x" src="https://github.com/fnando/breadcrumbs/assets/58574619/9425be29-f110-4bb8-b4f0-635815547787">
I cant access search. 
![CleanShot 2023-06-18 at 21 53 05@2x](https://github.com/fnando/breadcrumbs/assets/58574619/204e994e-cbcb-46a2-8a76-4ce20afd08b3)

There is any way to put this breadcrumb in before action, or I need to copy this in all actions?

**Comment by btrewern** [comment]
I don't think this is a bug.  I think you could do it as follows:

```ruby
before_action :search, only: [:index]
before_action :add_initial_breadcrumbs

...

private

...

def add_initial_breadcrumbs
    add_breadcrumb "Search: #{search.name}, search_path(search)
end
```

**Comment by mateuszbialowas** [comment]
@btrewern Thank you
