### ISSUE TITLE
It seems a problem to define own formatter

### ISSUE THREAD

**Issue by bananaappletw** [fnando/breadcrumbs#7]
wrong number of arguments (given 2, expected 0)
When initial own formatter, error prompt.
Code stop at this line
https://github.com/fnando/breadcrumbs/blob/master/lib/breadcrumbs.rb#L59

**Comment by fnando** [comment]
Hi,

Could you please post the complete backtrace for the example and a sample formatter that raises the exception? Thanks!

**Comment by bananaappletw** [comment]
![capture](https://user-images.githubusercontent.com/6241350/31400571-a5d130bc-ae22-11e7-8920-f9860b6a1fe6.PNG)

**Comment by bananaappletw** [comment]
app/controller/application.rb
```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :add_initial_breadcrumbs
  private
  def add_initial_breadcrumbs
    breadcrumbs.add "Home", root_path
  end
  class Breadcrumbs::Render::Dl
    def render
      ""
    end
  end
end
```

**Comment by fnando** [comment]
You have inherit from `Breadcrumbs::Render::Base`. Use [this formatter](https://github.com/fnando/breadcrumbs/blob/master/lib/breadcrumbs/render/list.rb) as a sample.
